zabbix_export:
  version: '7.0'
  template_groups:
    - uuid: 57b7ae836ca64446ba2c296389c009b7
      name: Templates/Modules
  templates:
    - uuid: e6cc0fb4cb4d4b4886502ff41e092abf
      template: 'Show OIDs values in HTML table PoC'
      name: 'Show OIDs values in HTML table PoC'
      groups:
        - name: Templates/Modules
      items:
        - uuid: 3884b959b88f458dac16a7d72cd35223
          name: 'HTML vertical'
          type: DEPENDENT
          key: getHtmlGroupedByRow
          delay: '0'
          history: 90d
          value_type: TEXT
          trends: '0'
          preprocessing:
            - type: JAVASCRIPT
              parameters:
                - |
                  
                  var json_array = JSON.parse(value);
                  
                  function getValues(obj) {
                      var result = [];
                  
                      for (i in obj) {
                          result.push(obj[i]);
                      }
                  
                      return result;
                  }
                  
                  function getHtmlGroupedByColumn(data) {
                      var header = [];
                      var rows = [];
                      var html = '<table style=\'{$CSS:table}\'>';
                  
                      for (i in data) {
                          var row = [];
                  
                          for (k in data[i]) {
                              header[k] = k;
                              row[k] = data[i][k];
                          }
                  
                          rows.push(getValues(row));
                      }
                  
                      html += '<tr><th style=\'{$CSS:table.th}\'>' + (getValues(header).join('</th><th style=\'{$CSS:table.th}\'>')) + '</th>';
                      for (i in rows) {
                          html += '<tr><td style=\'{$CSS:table.td}\'>' + (rows[i].join('</td><td style=\'{$CSS:table.td}\'>')) + '</td>';
                      }
                      html += '</table>';
                  
                      return html;
                  }
                  
                  function getHtmlGroupedByRow(data) {
                      var header = [];
                      var rows = [];
                      var html = '<table style=\'{$CSS:table}\'>';
                  
                      for (i in data) {
                          var row = [];
                  
                          for (k in data[i]) {
                              header[k] = k;
                              row[k] = data[i][k];
                          }
                  
                          rows.push(row);
                      }
                  
                      html += '<tr><td style=\'{$CSS:table.td}\'></td>';
                      var header_array = getValues(header);
                      for (i = 0; i < header_array.length; i++) {
                          html += '<th style=\'{$CSS:table.th}\'>' + (i + 1) + '</th>';
                      }
                      html += '</tr>';
                  
                      for (i in header) {
                          html += '<tr><th style=\'{$CSS:table.th}\'>' + i + '</th>';
                          for (j in rows) {
                              html += '<td style=\'{$CSS:table.td}\'>' + rows[j][i] + '</td>';
                          }
                          html += '</tr>';
                      }
                  
                      html += '</table>';
                  
                      return html;
                  }
                  
                  return getHtmlGroupedByRow(json_array);
          master_item:
            key: oids.input
        - uuid: 1c40fd39e9a147ed9809c2f7d2854d5a
          name: 'HTML horizontal'
          type: DEPENDENT
          key: HtmlGroupedByColumn
          delay: '0'
          history: 90d
          value_type: TEXT
          trends: '0'
          preprocessing:
            - type: JAVASCRIPT
              parameters:
                - |
                  
                  var json_array = JSON.parse(value);
                  
                  function getValues(obj) {
                      var result = [];
                  
                      for (i in obj) {
                          result.push(obj[i]);
                      }
                  
                      return result;
                  }
                  
                  function getHtmlGroupedByColumn(data) {
                      var header = [];
                      var rows = [];
                      var html = '<table style=\'border:1px gray solid\'>';
                  
                      for (i in data) {
                          var row = [];
                  
                          for (k in data[i]) {
                              header[k] = k;
                              row[k] = data[i][k];
                          }
                  
                          rows.push(getValues(row));
                      }
                  
                      html += '<tr><th style=\'border:1px gray dotted;font-weight:bold\'>' + (getValues(header).join('</th><th style=\'border:1px gray dotted;font-weight:bold\'>')) + '</th>';
                      for (i in rows) {
                          html += '<tr><td style=\'border:1px gray dotted\'>' + (rows[i].join('</td><td style=\'border:1px gray dotted\'>')) + '</td>';
                      }
                      html += '</table>';
                  
                      return html;
                  }
                  
                  function getHtmlGroupedByRow(data) {
                      var header = [];
                      var rows = [];
                      var html = '<table>';
                  
                      for (i in data) {
                          var row = [];
                  
                          for (k in data[i]) {
                              header[k] = k;
                              row[k] = data[i][k];
                          }
                  
                          rows.push(row);
                      }
                  
                      html += '<tr><td></td>';
                      var header_array = getValues(header);
                      for (i = 0; i < header_array.length; i++) {
                          html += '<th>' + (i + 1) + '</th>';
                      }
                      html += '</tr>';
                  
                      for (i in header) {
                          html += '<tr><th>' + i + '</th>';
                          for (j in rows) {
                              html += '<td>' + rows[j][i] + '</td>';
                          }
                          html += '</tr>';
                      }
                  
                      html += '</table>';
                  
                      return html;
                  }
                  
                  return getHtmlGroupedByColumn(json_array);
          master_item:
            key: oids.input
        - uuid: 661e3934409c4926b6df44eb6f2ecb45
          name: oids.input
          type: SNMP_AGENT
          snmp_oid: 'discovery[{#ALIAS},1.3.6.1.2.1.31.1.1.1.18,{#NAME},1.3.6.1.2.1.31.1.1.1.1,{#DESC},1.3.6.1.2.1.2.2.1.2]'
          key: oids.input
          delay: 1d
          history: 90d
          value_type: TEXT
          trends: '0'
          description: 'an API call which gets all items'
          preprocessing:
            - type: JSONPATH
              parameters:
                - '$.[0:{$RECORDS}]'
              error_handler: DISCARD_VALUE
          tags:
            - tag: Application
              value: api
        - uuid: 637584b512864b07b6fbc16a31954243
          name: Size
          type: DEPENDENT
          key: size.of.html
          delay: '0'
          preprocessing:
            - type: JAVASCRIPT
              parameters:
                - 'return value.length;'
          master_item:
            key: HtmlGroupedByColumn
      macros:
        - macro: '{$CSS:table}'
          value: 'border:1px gray solid'
        - macro: '{$CSS:table.td}'
          value: 'border:1px gray dotted'
        - macro: '{$CSS:table.th}'
          value: 'border:1px gray dotted;font-weight:bold'
        - macro: '{$RECORDS}'
          value: '50'
      dashboards:
        - uuid: 978737b62e7a4e3b85a276bc9f757797
          name: 'Unavailable hosts'
          display_period: '3600'
          pages:
            - name: Horizontal
              widgets:
                - type: itemhistory
                  width: '72'
                  height: '64'
                  fields:
                    - type: INTEGER
                      name: columns.0.display
                      value: '4'
                    - type: ITEM
                      name: columns.0.itemid
                      value:
                        host: 'Show OIDs values in HTML table PoC'
                        key: HtmlGroupedByColumn
                    - type: INTEGER
                      name: columns.0.monospace_font
                      value: '1'
                    - type: STRING
                      name: columns.0.name
                      value: HTML
                    - type: INTEGER
                      name: layout
                      value: '1'
                    - type: STRING
                      name: reference
                      value: AAAZE
                    - type: INTEGER
                      name: show_column_header
                      value: '0'
                    - type: INTEGER
                      name: show_lines
                      value: '1'
                    - type: INTEGER
                      name: sortorder
                      value: '1'
                    - type: STRING
                      name: time_period.from
                      value: now-1y
                    - type: STRING
                      name: time_period.to
                      value: now
            - name: Vertical
              widgets:
                - type: itemhistory
                  width: '72'
                  height: '64'
                  fields:
                    - type: INTEGER
                      name: columns.0.display
                      value: '4'
                    - type: ITEM
                      name: columns.0.itemid
                      value:
                        host: 'Show OIDs values in HTML table PoC'
                        key: getHtmlGroupedByRow
                    - type: INTEGER
                      name: columns.0.monospace_font
                      value: '1'
                    - type: STRING
                      name: columns.0.name
                      value: HTML
                    - type: INTEGER
                      name: layout
                      value: '1'
                    - type: STRING
                      name: reference
                      value: TVXTO
                    - type: INTEGER
                      name: show_column_header
                      value: '0'
                    - type: INTEGER
                      name: show_lines
                      value: '1'
                    - type: INTEGER
                      name: sortorder
                      value: '1'
                    - type: STRING
                      name: time_period.from
                      value: now-1y
                    - type: STRING
                      name: time_period.to
                      value: now
